services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tplayer
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 25000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ask@me.com
      PGADMIN_DEFAULT_PASSWORD: 123

