services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: rota66_dev

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
     - 12000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@taking.com.br
      PGADMIN_DEFAULT_PASSWORD: 123456
